config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static#home'

  get  '/auth/facebook/callback' => 'sessions#create' 
  get  '/login'          => 'sessions#new'
  get  '/signup'         => 'patients#new'
  post '/login'          => 'sessions#create'
  get  '/logout'         => 'sessions#destroy'
  get  '/conditions/:id' => 'conditions#destroy'
  get  '/drugs/:id'      => 'drugs#destroy'
  get  '/home'           => 'doctors#show'

  resources :doctors, only: [] do
    resources :appointments, only: [:index, :new, :create]
  end

  resources :patients, only: [:index, :show, :new, :create, :edit, :update] do
    resources :appointments, only: [:index, :show, :edit, :update, :destroy]
    # resources :conditions, only: :index
  end

end

app/models/patient.rb
class Patient < ActiveRecord::Base
   has_many :appointments
   has_many :doctors, through: :appointments
   
   has_many :patient_drugs
   has_many :drugs, through: :patient_drugs

   has_many :patient_conditions
   has_many :conditions, through: :patient_conditions

   validates :first_name, presence: true
   validates :surname, presence: true
   validates :date_of_birth, presence: true
   validates :password, presence: true, length: { minimum: 6 }
   validates_confirmation_of :email, :password
   validates_confirmation_of :password

   has_secure_password
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
   before_action :must_be_doctor_or_current_patient, except: [:new, :create]

   def new
      @patient = Patient.new
   end

   def create
      @patient = Patient.create(user_params)
      if @patient.errors.any?
         render 'new'
      else
         session[:patient_id] = @patient.id
         redirect_to patient_path(@patient)
      end
   end

   def show
      @patient = Patient.find(params[:id])
      active_drugs = Drug.active.select{ |drug| drug.patient_id == @patient.id }.sort
      @drug_interactions = find_drug_interactions(active_drugs)
      @drug_contraindications = find_drug_contraindications(active_drugs, @patient.conditions)
   end

   def index
      @patients = Patient.all.sort_by{ |patient| patient.surname }
   end
   
   private

   def user_params
      params.permit(:first_name, :middle_name, :surname, :date_of_birth, :email, :password, :password_confirmation)
   end
 
end

app/views/patients/index.html.erb
<h3>All patients</h3>
<br><br>
<table>
   <tr>
      <th>Name</th>
      <th>DOB</th>
      <th>Link</th>
      <th>Registration date</th>
   </tr>
   <% @patients.each do |patient| %>
   <tr>
      <td><%= "#{patient.surname.upcase}, #{patient.first_name} #{patient.middle_name}".squish %></td>
      <td><%= patient.date_of_birth.strftime('%d/%m/%Y') unless patient.date_of_birth == nil %></td>
      <td><%= link_to "(view)", patient_path(patient) %></td>
      <td><%= patient.created_at.strftime('%d/%m/%Y') %></td>
   </tr>
   <% end %>

app/views/patients/new.html.erb
<h4>Sign up as a new patient</h4>
<p>Please note that you may only sign up as a patient. If you are a consultant, please contact your system administrator for a practitioner's account.</p>


<% if @patient.errors.any? %>
   <p class="error"><b><%= "There were some errors with your signup:" %></b></p>
   <ul>
   <% @patient.errors.full_messages.each do |message| %>
      <li><%= message %></li>
   <% end %>
   </ul>
<% end %>
* compulsory fields
<br>
<br>

<%= form_for @patient do |f| %>
   
  <div class="form-group">
    <%= label_tag(:first_name) %>*
    <%= text_field_tag(:first_name, nil, class: "form-control") %>
  </div>

  <div class="form-group">
    <%= label_tag(:middle_name, "Middle name (if applicable)") %>
    <%= text_field_tag(:middle_name, nil, class: "form-control") %>
  </div>

  <div class="form-group">
    <%= label_tag(:surname) %>*
    <%= text_field_tag(:surname, nil, class: "form-control") %>
  </div>

   <div class="form-group">
    <%= label_tag(:date_of_birth) %>*
    <%= date_field_tag(:date_of_birth, nil, class: "form-control") %>
  </div>

   <div class="form-group">
    <%= label_tag(:email) %>*
    <%= text_field_tag(:email, nil, class: "form-control") %>
  </div>

   <div class="form-group">
    <%= label_tag(:password) %>*
    <%= password_field_tag(:password, nil, class: "form-control") %>
  </div>

   <div class="form-group">
    <%= label_tag(:password_confirmation) %>*
    <%= password_field_tag(:password_confirmation, nil, class: "form-control") %>
  </div>

   <div class="actions">
      <br/>
      <%= f.submit "Sign up as new patient", class: "btn btn-primary" %>
   </div>

<% end %>

app/views/patients/show.html.erb
<h3>Medical record: <%= full_name(@patient) %></h3>
<% if @patient.date_of_birth %>
   <p><b>Date of Birth:</b> <%= @patient.date_of_birth.strftime('%d/%m/%Y') if @patient.date_of_birth %></p>
<% end %>
<br>
<% if @patient.appointments.any? %>
   <p><b>Appointment Schedule</b></p>
   <table>
      <tr>
         <th>Appointment date</th>
         <th>Diagnosis</th>
         <th>Drug prescribed</th>
         <th>To be taken until</th>
         <th>Current drug?</th>
         <th>Appointment link</th>
      </tr>
      <% @patient.appointments.sort_by{ |appointment| appointment.date }.reverse!.each do |appointment| %>
         <tr>
            <td><%= appointment.date.strftime('%d/%m/%Y') %></td>
            <td>
            <% if @patient.conditions.find_by(name: appointment.diagnosis.downcase) %>
               <%= appointment.diagnosis %>
               <%= link_to "(remove)", "/conditions/#{@patient.conditions.find_by(name: appointment.diagnosis.downcase).id}" if session[:doctor_id] %>
            <% end %>
            </td>
            <% if @patient.drugs.find_by(name: appointment.drug_prescribed) %>
               <% patientdrug = PatientDrug.find_by(patient_id: @patient.id, drug_id: Drug.find_by(name: appointment.drug_prescribed)) %>
               <td>
                  <%= appointment.drug_prescribed %>
                  <%= link_to "(remove)", "/drugs/#{@patient.drugs.find_by(name: appointment.drug_prescribed).id}" if session[:doctor_id] %>
               </td>
               <td>
                  <%= patientdrug.prescription_expiry.strftime('%d/%m/%Y') %>
               </td>
               <td>
                  <%= patientdrug.prescription_expiry > Time.now ? "Yes" : "No" %>
               </td>
            <% else %>
               <td></td><td></td><td>No</td>
            <% end %>
            <td><%= link_to "(view)", patient_appointment_path(patient_id: @patient, id: appointment) %>
         </tr>
      <% end %>
   </table>
<br>
<p><b>Note:</b><br> This is a reflection of the active conditions of the patient, so some conditions/drugs may be missing if a condition is no longer present or if a drug has been deemed unsuitable for the patient. 
If more information is required from an appointment, please visit the appointment's main view.</p>
<% else %>
   <p>No records created yet.</p>
<% end %>
<br>
<% if @drug_interactions.any? %>
   <br>
   <h3>Interactions</h3>
   <% @drug_interactions.each do |d| %>
      <p class="error"><b><%= d[0].drug_1 %> and <%= d[0].drug_2 %></b></p>
      <p><%= d[0].info %></p>
   <% end %>
<% end %>

<% if @drug_contraindications.any? %>
   <br>
   <h3>Contra-Indications</h3>
   <% @drug_contraindications.each do |contra| %>
      <p><%= contra %></p>
   <% end %>
<% end %>