config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static#home'

  get  '/auth/facebook/callback' => 'sessions#create' 
  get  '/login'          => 'sessions#new'
  get  '/signup'         => 'patients#new'
  post '/login'          => 'sessions#create'
  get  '/logout'         => 'sessions#destroy'
  get  '/conditions/:id' => 'conditions#destroy'
  get  '/drugs/:id'      => 'drugs#destroy'
  get  '/home'           => 'doctors#show'

  resources :doctors, only: [] do
    resources :appointments, only: [:index, :new, :create]
  end

  resources :patients, only: [:index, :show, :new, :create, :edit, :update] do
    resources :appointments, only: [:index, :show, :edit, :update, :destroy]
    # resources :conditions, only: :index
  end

end

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <title>SecMed</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  </head>
  <style>
    table {
      font-family: arial, sans-serif;
      border-collapse: collapse;
      width: 100%;
    }

    .error {
      color: red;
    }

    td, th {
      border: 1px solid #dddddd;
      text-align: left;
      padding: 7px;
    }

    tr:nth-child(even) {
      background-color: #ddfaff;
    }
  </style>
  <body>
    <div class="container">
      <h1>SecMed <b>☤</b></h1>
      <h4>Flatiron Clinic</h4>
      <br>
      <%= link_to "Home", root_path %>   
      <% if logged_in? %>
        <% if session.to_h.has_key?("patient_id") %>
          <%= link_to "My appointments", patient_appointments_path(session[:patient_id]) %>   
          <%= link_to "My medical record", patient_path(session[:patient_id]) %>   
        <% elsif session.to_h.has_key?("doctor_id") %>
          <%= link_to "Appointments", doctor_appointments_path(session[:doctor_id]) %>   
          <%= link_to "View all patients", patients_path %>   
          <%= link_to "New appointment", new_doctor_appointment_path(session[:doctor_id]) %>   
        <% end %>
        <%= link_to "Log out", logout_path %>
      <% else %>

        <%= link_to "Sign up", '/signup' %>   
        <%= link_to "Log in", login_path %>   
        <%= link_to "Log in with Facebook", '/auth/facebook' %>   
      <% end %>
      <br><br>
      <%= yield %>

      <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    </div>
  </body>
</html>